name: Debug Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug Info
        run: |
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          
      - name: Check Node.js
        run: |
          node --version
          npm --version
          
      - name: Check Directory Structure
        run: |
          ls -la
          ls -la SMS_V.2.0/
          
      - name: Check Package.json
        run: |
          cat SMS_V.2.0/package.json | head -20
          
      - name: Test npm install
        working-directory: SMS_V.2.0
        run: |
          npm ci --dry-run