# DISABLED: This workflow is disabled due to repository ownership restrictions
# To re-enable, transfer repository ownership to "hersouls" organization

name: Security & Dependencies (DISABLED)

# on:
#   schedule:
#     # 매주 월요일 오전 9시에 실행
#     - cron: '0 9 * * 1'
#   workflow_dispatch: # 수동 실행 가능

jobs:
  # 보안 취약점 검사
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: SMS_V.2.0/package-lock.json
        
    - name: Install dependencies
      run: |
        cd SMS_V.2.0
        npm ci
        
    - name: Run security audit
      run: |
        cd SMS_V.2.0
        npm audit --audit-level=moderate
        
    - name: Run npm outdated check
      run: |
        cd SMS_V.2.0
        npm outdated || true

  # 의존성 업데이트 (Dependabot 대안)
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: SMS_V.2.0/package-lock.json
        
    - name: Install dependencies
      run: |
        cd SMS_V.2.0
        npm ci
        
    - name: Update dependencies
      run: |
        cd SMS_V.2.0
        npm update
        
    - name: Check for updates
      id: check-updates
      run: |
        cd SMS_V.2.0
        if git diff --quiet package-lock.json; then
          echo "no-updates=true" >> $GITHUB_OUTPUT
        else
          echo "no-updates=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push updates
      if: steps.check-updates.outputs.no-updates == 'false'
      run: |
        cd SMS_V.2.0
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package-lock.json
        git commit -m "chore: update dependencies [skip ci]"
        git push